name: Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        choco install cmake -y
        choco install googletest -y

    - name: setup and run linter
      run: |
        pip install cpplint
        cpplint --filter=-legal --linelength=100 *.cpp

    - name: tshirts fail
      run: |
        cmake -S . -B build
        cmake --build build --config Release
        build\Release\test_tshirts.exe
        bash .github/workflows/expectfail.sh build\Release\test_tshirts.exe

    - name: misaligned fail
      run: |
        cmake -S . -B build
        cmake --build build --config Release
        build\Release\test_misaligned.exe
        bash .github/workflows/expectfail.sh build\Release\test_misaligned.exe

    - name: alerter fail
      run: |
        cmake -S . -B build
        cmake --build build --config Release
        build\Release\test_weatherreport.exe
        bash .github/workflows/expectfail.sh build\Release\test_weatherreport.exe