name: Build and Run

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev
        sudo apt-get install -y cmake
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make

    - name: setup and run linter
      run: |
        pip install cpplint
        cpplint --filter=-legal --linelength=100 *.cpp

    - name: tshirts fail
      run: |
        g++ -Wall -Wextra -Werror -lgtest -lgtest_main test_tshirts.cpp -o tshirts.out
        bash .github/workflows/expectfail.sh ./tshirts.out

    - name: misaligned fail
      run: |
        g++ -Wall -Wextra -Werror -lgtest -lgtest_main test_misaligned.cpp -o misaligned.out
        bash .github/workflows/expectfail.sh ./misaligned.out

    - name: alerter fail
      run: |
        g++ -Wall -Wextra -Werror -lgtest -lgtest_main test_weatherreport.cpp -o weatherreport.out
        bash .github/workflows/expectfail.sh ./weatherreport.out